version: '2'
services:
  identity-provider:
    build: .
    expose:
      - 3000
    environment:
      - MAIL_FROM=no-reply@rts.ch
      - IDP_HOST=http://localhost:3000
      - IDP_RECAPCHA_SITEKEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - IDP_RECAPCHA_SECRETKEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      - DEFAULT_LOCALE=fr
      - DB_DATABASE=idp
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dockeridp
      - DB_PASSWORD=SchiefesHausBautFalsch
      - MAIL_TRANSPORT_TYPE=test
      - TRACKING_COOKIE=true
      - SESSION_SECRET=LKASDMjnr234n90lasndfsadf
      - AUTH_SESSION_COOKIE_ACCESSIBLE_OVER_NON_HTTPS=false
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    build: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BlinkenderWaldRegnetFrohlich
      - DOCKER_USER=dockeridp
      - DOCKER_PASSWORD=SchiefesHausBautFalsch
  proxy:
    build: ./nginx
    ports:
    - 3000:3000
    links:
    - identity-provider