# run using: docker-compose -f docker-compose-rts.yaml up
version: '2'
services:
  identity-provider:
    restart: always
    build: .
    ports:
    - 3000:3000
    environment:
    - BASE_URL=https://cpa.rts.ch
    - MAIL_FROM=no-reply@rts.ch
    - IDP_HOST=http://localhost:3000
    - IDP_RECAPCHA_SITEKEY=6Lc6NCYUAAAAAPiyvFO2jig6jXGtYEhgZWtWFzml
    - IDP_RECAPCHA_SECRETKEY=6Lc6NCYUAAAAALCXdWXUsZgDBl7fn9XA_ecVpu7m
    - DEFAULT_LOCALE=fr
    - OPEN_AM_ENABLED=true
    - OPEN_AM_SERVICE_URL=https://sso.rts.ch/
    - MAIL_TRANSPORT_TYPE=test
    - MAIL_USER_NAME=username
    - MAIL_PASSWORD=password
    - TRACKING_COOKIE=true
    - IDP_CLIENT_URL=http://hummingbird-sandbox-marts.rts.ch
    - BROADCASTER_LAYOUT=rts
    - MAIL_DEFAULT_TEMPLATE_CLASS=rts
    - AUTO_IDP_REDIRECT=local
    - DISPLAY_MENU_BAR=
    - IDP_TITLE=Radio Télévision Suisse - Fournisseur d'identité
    - FACEBOOK_LOGIN_ENABLED=true
    - FACEBOOK_LOGIN_ID=1987072604859726
    - FACEBOOK_LOGIN_SECRET=eb01cbc36d070e6c86ad3e697bebdca1
    - GOOGLE_LOGIN_ENABLED=true
    - GOOGLE_LOGIN_ID=621117323323-j048lcbv5khh6lhr1lok4vv17mekijvm.apps.googleusercontent.com
    - GOOGLE_LOGIN_SECRET=rw1KMzemV5Mhtjq1iOAI4H8A
    - SESSION_SECRET=LKASDMjnr234n90lasndfsadf
    - AUTH_SESSION_COOKIE_ACCESSIBLE_OVER_NON_HTTPS=true
  nginx:
    image: nginx
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx/conf:/etc/nginx/:ro
    - ./nginx/ssl:/etc/ssl/certs:ro
