version: '2'
services:
  identity-provider:
    build: .
    ports:
      - 3000:3000
      - 9022:9022
    environment:
      - MAIL_FROM=no-reply@rts.ch
      - IDP_HOST=http://localhost:3000
      - IDP_RECAPCHA_SITEKEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      - IDP_RECAPCHA_SECRETKEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      - DEFAULT_LOCALE=fr
      - DB_DATABASE=idp
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dockeridp
      - DB_PASSWORD=SchiefesHausBautFalsch
      - MAIL_TRANSPORT_TYPE=test
      - TRACKING_COOKIE=true
      - CUSTOM_OAUTH_MSG={client} souhaite accéder à votre compte maRTS.
      - SESSION_SECRET=LKASDMjnr234n90lasndfsadf
      - AUTH_SESSION_COOKIE_ACCESSIBLE_OVER_NON_HTTPS=true
    depends_on:
      - postgres
    links:
      - postgres:postgres
    #command: bash -c "sequelize db:migrate && bin/prep-db && bin/server"
  postgres:
    build: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BlinkenderWaldRegnetFrohlich
      - DOCKER_USER=dockeridp
      - DOCKER_PASSWORD=SchiefesHausBautFalsch
  oauth2-client:
    build: oauth2-client
    ports:
    - 3001:3001
    environment:
    - OAUTH2_CLIENT_ID=db05acb0c6ed902e5a5b7f5ab79e7144
    - OAUTH2_CLIENT_SECRET=49b7448061fed2319168eb2449ef3b58226a9c554b3ff0b138abe8ffad98
    - OAUTH2_SERVER=http://localhost:3000
    - OAUTH2_CALLBACK=http://localhost:3001
    - OAUTH2_INTERNAL_SERVER=http://identity-provider:3000
    links:
    - identity-provider:identity-provider
